export {default as Loader} from './Loader.components'
export { default as Footer } from './Footer.components'
export { default as Navbar } from './Navbar.component.jsx'
export { default as Transactions } from './Transactions.components'
export { default as Welcome } from './Welcome.components'
export { default as Services } from './Services.components'
